#!/usr/bin/env bash
# doc2md_setup.sh — Interactive setup for doc2md API credentials
# Run with: ! bash doc2md_setup.sh /path/to/folder
#
# Writes a .doc2md.env file to the target folder.
# The API key is captured with hidden input and NEVER printed to stdout,
# so it stays out of Claude's conversation context.

set -euo pipefail

FOLDER="${1:-.}"
FOLDER="$(cd "$FOLDER" && pwd)"
ENV_FILE="$FOLDER/.doc2md.env"

echo "=== Doc2MD Setup ==="
echo "Target folder: $FOLDER"
echo ""

# Check for existing config
if [[ -f "$ENV_FILE" ]]; then
    echo "Existing config found at $ENV_FILE"
    read -rp "Overwrite? (y/N): " overwrite
    if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
        echo "Keeping existing config."
        exit 0
    fi
fi

# Choose provider
echo ""
echo "Choose your LLM provider:"
echo "  1) OpenRouter (cloud — requires API key)"
echo "  2) Ollama (local — API key optional)"
echo ""
read -rp "Enter 1 or 2: " choice

case "$choice" in
    1)
        PROVIDER="openrouter"
        DEFAULT_MODEL="google/gemini-2.5-flash"
        echo ""
        read -sp "Enter your OpenRouter API key: " api_key
        echo ""
        if [[ -z "$api_key" ]]; then
            echo "Error: API key is required for OpenRouter."
            exit 1
        fi
        ;;
    2)
        PROVIDER="ollama"
        DEFAULT_MODEL="gemma4"
        echo ""
        read -sp "Enter Ollama API key (press Enter to skip): " api_key
        echo ""
        if [[ -z "$api_key" ]]; then
            api_key="ollama"
        fi
        ;;
    *)
        echo "Invalid choice."
        exit 1
        ;;
esac

# Optional: custom model
echo ""
read -rp "Model name (Enter for default: $DEFAULT_MODEL): " custom_model
MODEL="${custom_model:-$DEFAULT_MODEL}"

# Optional: custom Ollama URL
OLLAMA_URL="http://localhost:11434/v1"
if [[ "$PROVIDER" == "ollama" ]]; then
    read -rp "Ollama URL (Enter for default: $OLLAMA_URL): " custom_url
    OLLAMA_URL="${custom_url:-$OLLAMA_URL}"
fi

# Write the env file
cat > "$ENV_FILE" <<ENVEOF
# Doc2MD configuration — generated by doc2md_setup.sh
# DO NOT commit this file or share it.
DOC2MD_PROVIDER=$PROVIDER
DOC2MD_MODEL=$MODEL
ENVEOF

if [[ "$PROVIDER" == "openrouter" ]]; then
    echo "OPENROUTER_API_KEY=$api_key" >> "$ENV_FILE"
else
    echo "OLLAMA_API_KEY=$api_key" >> "$ENV_FILE"
    echo "OLLAMA_URL=$OLLAMA_URL" >> "$ENV_FILE"
fi

echo ""
echo "Config saved to $ENV_FILE"
echo "Provider: $PROVIDER"
echo "Model: $MODEL"
[[ "$PROVIDER" == "ollama" ]] && echo "Ollama URL: $OLLAMA_URL"
echo ""
echo "Done! You can now use /doc2md on this folder."
